apiVersion: v2
name: voting-app
description: A production-grade Helm chart for the Voting Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - voting
  - microservices
  - flask
  - nodejs
  - dotnet
home: https://github.com/omarMohamedo-o/tactful-votingapp-cloud-infra
sources:
  - https://github.com/omarMohamedo-o/tactful-votingapp-cloud-infra
maintainers:
  - name: Omar
    email: omar@example.com
