---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: voting-app
data:
  OPTION_A: "Cats"
  OPTION_B: "Dogs"
  REDIS_HOST: "redis"
  POSTGRES_HOST: "db"
  POSTGRES_DB: "postgres"
  VOTE_PORT: "80"
  RESULT_PORT: "4000"
